version: "2"

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true

# SEE: https://golangci-lint.run/docs/configuration/file/
linters:
  default: all
  disable:
    - varnamelen # [great idea, but too many false positives] checks that the length of a variable's name matches its scope
    - exhaustruct
    - depguard
    - tagalign
    - rowserrcheck # was disabled because of generics
    - sqlclosecheck # was disabled because of generics
    - wastedassign # was disabled because of generics
  settings:
    cyclop:
      # the maximal code complexity to report
      max-complexity: 12
      # the maximal average package complexity. If it's higher than 0.0 (float) the check is enabled (default 0.0)
      package-average: 0.0
    dupl:
      # tokens count to trigger issue, 150 by default
      threshold: 200
    errcheck:
      # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
      # default is false: such cases aren't reported by default.
      check-type-assertions: false
      # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
      # default is false: such cases aren't reported by default.
      check-blank: false
    funlen:
      # default is 60
      lines: 70
      # default is 40
      statements: 40
    gocognit:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 20
    goconst:
      # minimal length of string constant, 3 by default
      min-len: 3
      # minimal occurrences count to trigger, 3 by default
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - paramTypeCombine
    gocyclo:
      # minimal code complexity to report, 30 by default (but we recommend 10-20)
      min-complexity: 15
    godox:
      keywords:
        - "BUG"
        - "FIXME"
    govet:
      # Enable all analyzers.
      enable-all: true
      # Disable analyzers by name.
      disable:
        - fieldalignment # too strict
      settings:
        shadow:
          # Whether to be strict about shadowing; can be noisy.
          strict: true
    lll:
      line-length: 120 # 120 is default
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: snake
          yaml: snake
    misspell:
      locale: US
    mnd:
      # List of function patterns to exclude from analysis.
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
        - io.Reader
        - io.Writer
        - \*cli.Context
    nakedret:
      # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
      max-func-lines: 30
    unparam:
      # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
      check-exported: false
    wrapcheck:
      # An array of glob patterns to exclude from wrap-checking.
      ignorePackageGlobs:
        - encoding/*
        - github.com/pkg/*
    wsl:
      # If true append is only allowed to be cuddled if appending value is
      # matching variables, fields or types on line above. Default is true.
      strict-append: true
      # Allow calls and assignments to be cuddled as long as the lines have any
      # matching variables, fields or types. Default is true.
      allow-assign-and-call: true
      # Allow multiline assignments to be cuddled. Default is true.
      allow-multiline-assign: true
      # Allow declarations (var) to be cuddled.
      allow-cuddle-declarations: true
      # Allow trailing comments in ending of blocks
      allow-trailing-comment: true
      # Force newlines in end of case at this limit (0 = never).
      force-case-trailing-whitespace: 0
  exclusions:
    paths:
      - vendor$
      - _test\.go$
    rules:
      - text: "Version`? is a global variable"
        linters:
          - gochecknoglobals
      - text: "cognitive complexity \\d+ of func `Interactive` is high"
        linters:
          - gocognit
      - source: "^//\\s*go:generate\\s"
        linters:
          - lll
      - source: "(noinspection|TODO)"
        linters:
          - godot
      - source: "//noinspection"
        linters:
          - gocritic

formatters:
  enable:
    - goimports
  settings:
    goimports:
      # put imports beginning with prefix after 3rd-party packages
      local-prefixes: github.com/gorcon/rcon-cli
